import { Blog } from '../models/Blog.js';
import { User } from '../models/User.js';
import { asyncHandler } from '../middleware/error.js';
import { runAutoBlogGeneration } from '../cron/autoBlogGenerator.js';
import { QueryOptimizer } from '../utils/performance.js';
import { cache } from '../utils/cache.js';

const getAdminEmails = () => {
  const configured = process.env.ADMIN_EMAILS;
  const defaults = ['system@vibeblog.ai'];

  if (!configured) return defaults;

  return configured
    .split(',')
    .map(email => email.trim().toLowerCase())
    .filter(Boolean);
};

/**
 * Create new blog
 */
export const createBlog = asyncHandler(async (req, res) => {
  const { title, content, category } = req.body;
  const userId = req.userId;

  if (!title || !content) {
    return res.status(400).json({ message: 'Please provide title and content' });
  }

  const blog = new Blog({
    title,
    content,
    category: category || 'General',
    author: userId,
    autoGenerated: false,
  });

  // Add image if provided
  if (req.imageUrl) {
    blog.imageUrl = req.imageUrl;
  }

  await blog.save();
  cache.clear();

  res.status(201).json({
    message: 'Blog created successfully',
    blog,
  });
});

/**
 * Get all blogs with pagination and filtering
 * Age-based visibility:
 * - < 1 week: visible to everyone
 * - 1 week - 1 month: visible only to logged-in users
 * - > 1 month: automatically deleted (shouldn't be queried)
 */
export const getAllBlogs = asyncHandler(async (req, res) => {
  const { page = 0, limit = 9, category } = req.query;
  const skip = parseInt(page) * parseInt(limit);

  const filter = {};

  // Category filtering
  if (category && category !== 'All') {
    filter.category = category;
  }

  // Age-based visibility filtering
  const now = new Date();
  const oneWeekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);

  if (!req.userId) {
    // Unauthenticated: Only show blogs from the last 7 days
    filter.createdAt = { $gte: oneWeekAgo };
  } else {
    // Authenticated: Show all blogs (they're older than 1 month are deleted by cron)
    // No additional date filter needed
  }

  const blogs = await Blog.find(filter)
    .sort({ createdAt: -1 })
    .skip(skip)
    .limit(parseInt(limit))
    .populate('author', 'name email');

  const total = await Blog.countDocuments(filter);

  res.status(200).json({
    blogs,
    total,
    page: parseInt(page),
    pages: Math.ceil(total / parseInt(limit)),
  });
});

/**
 * Get single blog by ID or slug
 */
export const getBlogById = asyncHandler(async (req, res) => {
  const { id } = req.params;

  // Build query to search by slug or ID
  const query = {
    $or: [
      { slug: id } // Try slug first
    ]
  };

  // Only try ObjectId if id looks like a valid MongoDB ID
  if (/^[0-9a-fA-F]{24}$/.test(id)) {
    query.$or.push({ _id: id });
  }

  // Try to find by slug first (more user-friendly), then by ID
  let blog = await Blog.findOne(query).populate('author', 'name email');

  if (!blog) {
    return res.status(404).json({ message: 'Blog not found' });
  }

  // Increment views
  blog = await Blog.findByIdAndUpdate(
    blog._id,
    { $inc: { views: 1 } },
    { new: true }
  ).populate('author', 'name email');

  res.status(200).json(blog);
});

/**
 * Get user's blogs
 */
export const getUserBlogs = asyncHandler(async (req, res) => {
  const userId = req.userId;

  const blogs = await Blog.find({ author: userId })
    .sort({ createdAt: -1 })
    .populate('author', 'name email');

  res.status(200).json(blogs);
});

/**
 * Update blog
 */
export const updateBlog = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const userId = req.userId;
  const { title, content, category } = req.body;

  const blog = await Blog.findById(id);

  if (!blog) {
    return res.status(404).json({ message: 'Blog not found' });
  }

  // Check if user is author
  if (blog.author.toString() !== userId) {
    return res.status(403).json({ message: 'Not authorized to update this blog' });
  }

  // Update fields
  if (title) blog.title = title;
  if (content) blog.content = content;
  if (category) blog.category = category;

  // Update image if new one was uploaded and processed
  if (req.imageUrl) {
    blog.imageUrl = req.imageUrl;
  }

  await blog.save();
  cache.clear();

  res.status(200).json({
    message: 'Blog updated successfully',
    blog,
  });
});

/**
 * Delete blog
 */
export const deleteBlog = asyncHandler(async (req, res) => {
  const { id } = req.params;
  const userId = req.userId;

  const blog = await Blog.findById(id);

  if (!blog) {
    return res.status(404).json({ message: 'Blog not found' });
  }

  // Check if user is author
  if (blog.author.toString() !== userId) {
    return res.status(403).json({ message: 'Not authorized to delete this blog' });
  }

  await Blog.findByIdAndDelete(id);
  cache.clear();

  res.status(200).json({ message: 'Blog deleted successfully' });
});

/**
 * Get trending blogs (auto-generated)
 */
export const getTrendingBlogs = asyncHandler(async (req, res) => {
  const limit = parseInt(req.query.limit) || 6;

  const blogs = await Blog.find({ autoGenerated: true })
    .sort({ views: -1, createdAt: -1 })
    .limit(limit)
    .populate('author', 'name email');

  res.status(200).json(blogs);
});

/**
 * Admin: Manually trigger trend blog generation
 */
export const triggerAutoBlogGeneration = asyncHandler(async (req, res) => {
  const user = await User.findById(req.userId).select('email name');

  if (!user) {
    return res.status(404).json({ message: 'User not found' });
  }

  const adminEmails = getAdminEmails();
  const isAdmin = adminEmails.includes(user.email?.toLowerCase());

  if (!isAdmin) {
    return res.status(403).json({
      message: 'Only admins can trigger auto-blog generation',
    });
  }

  await runAutoBlogGeneration(`manual API trigger by ${user.email}`);

  res.status(200).json({
    message: 'Auto-blog generation run completed',
  });
});
