import mongoose from 'mongoose';

const blogSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: [true, 'Please provide a title'],
      trim: true,
      maxlength: [200, 'Title cannot exceed 200 characters'],
    },
    slug: {
      type: String,
      unique: true,
      lowercase: true,
      sparse: true,
    },
    content: {
      type: String,
      required: [true, 'Please provide content'],
      minlength: [10, 'Content must be at least 10 characters'],
    },
    category: {
      type: String,
      enum: [
        'Technology',
        'Business',
        'Science',
        'Health',
        'Sports',
        'Economy',
        'Environment',
        'Education',
        'General',
      ],
      default: 'General',
    },
    // Image storage - now only URL-based for better performance
    imageUrl: {
      type: String, // Stored image URL (for uploads) or Unsplash URL
    },
    unsplashAttribution: {
      unsplashPhotoId: String,
      photographerName: String,
      photographerUsername: String,
      photographerUrl: String,
      unsplashUrl: String, // Direct link to photo on Unsplash
      downloadTrackingUrl: String, // Unsplash download tracking endpoint
    },
    // Trending topic metadata from Groq
    trendingMetadata: {
      region: String, // e.g., 'US', 'Europe', 'Asia'
      importance: {
        type: Number,
        min: 1,
        max: 10,
      }, // Importance score from 1-10
      description: String, // Why this topic is trending
    },
    author: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    autoGenerated: {
      type: Boolean,
      default: false,
    },
    views: {
      type: Number,
      default: 0,
    },
  },
  { timestamps: true }
);

/**
 * Slug generation helper function
 */
const generateSlug = text => {
  return text
    .toLowerCase()
    .trim()
    .replace(/[^\w\s-]/g, '') // Remove special characters
    .replace(/\s+/g, '-') // Replace spaces with hyphens
    .replace(/-+/g, '-') // Replace multiple hyphens with single hyphen
    .slice(0, 50); // Limit length
};

/**
 * Generate slug before saving
 */
blogSchema.pre('save', async function (next) {
  if (!this.slug && this.title) {
    let slug = generateSlug(this.title);
    let uniqueSlug = slug;
    let counter = 1;

    // Ensure slug is unique
    while (await mongoose.model('Blog').findOne({ slug: uniqueSlug, _id: { $ne: this._id } })) {
      uniqueSlug = `${slug}-${counter}`;
      counter++;
    }

    this.slug = uniqueSlug;
  }

  next();
});

/**
 * Indexes for faster queries
 */
blogSchema.index({ category: 1, createdAt: -1 });
blogSchema.index({ author: 1 });
blogSchema.index({ autoGenerated: 1 });
blogSchema.index({ createdAt: -1 });
blogSchema.index({ autoGenerated: 1, createdAt: -1 });
blogSchema.index({ slug: 1 }); // For slug-based lookups

/**
 * Populate author before returning
 */
blogSchema.pre(/^find/, function (next) {
  if (this.options._recursed) return next();

  this.populate({
    path: 'author',
    select: 'name email',
  });

  next();
});

/**
 * Blog model
 */
export const Blog = mongoose.model('Blog', blogSchema);
