import cron from 'node-cron';
import axios from 'axios';
import { OpenAI } from 'openai';
import { Blog } from '../models/Blog.js';
import { User } from '../models/User.js';
import { cache } from '../utils/cache.js';

/**
 * Lazy initialize Groq client via OpenAI SDK (only when first used)
 */
let groq = null;
let isAutoBlogGenerationRunning = false;

const getGroqClient = () => {
  if (!groq) {
    groq = new OpenAI({
      apiKey: process.env.GROQ_API_KEY,
      baseURL: 'https://api.groq.com/openai/v1',
    });
  }
  return groq;
};

const REQUIRED_ENV_KEYS = ['GROQ_API_KEY'];

const hasRequiredApiKeys = () => {
  const missing = REQUIRED_ENV_KEYS.filter(key => !process.env[key]);
  if (missing.length > 0) {
    console.warn(`⚠ Skipping auto-blog generation. Missing env var(s): ${missing.join(', ')}`);
    return false;
  }
  return true;
};

const hasUnsplashKey = () => Boolean(process.env.UNSPLASH_ACCESS_KEY);

/**
 * Trend discovery configuration
 */
const TREND_CONFIG = {
  regions: [
    'US',
    'Europe',
    'Asia',
    'Africa',
    'South America',
    'Australia',
    'Middle East',
    'North America',
  ],
  categories: [
    'Technology',
    'Business',
    'Science',
    'Health',
    'Sports',
    'Economy',
    'Environment',
    'Education',
    'General',
  ],
  importanceThreshold: 6, // Only create blogs for topics with 6+ importance
  maxTopicsPerRun: 10, // Max topics Groq returns
  maxBlogsPerRun: 9, // Allow a single run to potentially cover all categories
  coverageWindowDays: 7, // Category balancing looks at recent 7-day distribution
};

const IMAGE_DIVERSITY_WINDOW_DAYS = 14;

const normalizeCategory = value => (TREND_CONFIG.categories.includes(value) ? value : 'General');

const normalizeTitleFingerprint = title =>
  String(title || '')
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

const shuffleArray = items => {
  const arr = [...items];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
};

const getRecentCategoryCoverage = async () => {
  const coverageWindowStart = new Date();
  coverageWindowStart.setDate(coverageWindowStart.getDate() - TREND_CONFIG.coverageWindowDays);

  const recentCategoryCounts = await Blog.aggregate([
    {
      $match: {
        autoGenerated: true,
        createdAt: { $gte: coverageWindowStart },
      },
    },
    {
      $group: {
        _id: '$category',
        count: { $sum: 1 },
      },
    },
  ]);

  const categoryCountMap = new Map(TREND_CONFIG.categories.map(category => [category, 0]));
  for (const item of recentCategoryCounts) {
    categoryCountMap.set(item._id, item.count);
  }

  const missingCategories = TREND_CONFIG.categories.filter(
    category => (categoryCountMap.get(category) ?? 0) === 0
  );

  return { categoryCountMap, missingCategories };
};

/**
 * Fetch trending topics from Groq API for multiple regions and categories
 * Returns structured data with importance scoring
 */
const fetchTrendingTopicsFromGroq = async preferredCategories => {
  try {
    console.log('📡 Fetching trending topics from Groq...');

    const regionsStr = TREND_CONFIG.regions.join(', ');
    const categoriesStr = TREND_CONFIG.categories.join(', ');

    const preferredCategoriesInstruction =
      preferredCategories && preferredCategories.length > 0
        ? `\nPRIORITY COVERAGE: Include at least one topic for each of these categories if available: ${preferredCategories.join(
            ', '
          )}.`
        : '';

    const prompt = `You are a global news analyst AI. Your task is to identify currently trending topics right now (as of ${new Date().toDateString()}).

Instructions:
1. Identify the top ${TREND_CONFIG.maxTopicsPerRun} trending topics right now across these regions: ${regionsStr}
2. Focus on these categories: ${categoriesStr}
3. For each topic, provide:
   - A clear, engaging title (as a news headline)
   - The region where it's trending (pick from: ${regionsStr})
   - The category (pick from: ${categoriesStr})
   - An importance score from 1-10 (where 10 = major global impact)
   - A brief description of why it's trending

IMPORTANT FILTERS:
- Exclude political news unless it's about major policy/infrastructure changes
- Exclude highly controversial or divisive topics
- Exclude celebrity gossip or entertainment drama
- Focus on substantive, informative, and engaging topics
- Ensure topics are FACTUAL and verifiable
${preferredCategoriesInstruction}

Return ONLY a valid JSON array with no markdown formatting, starting with [ and ending with ]. Example structure:
[
  {"title": "AI Breakthrough in Medical Diagnostics", "region": "US", "category": "Science", "importance": 9, "description": "New AI model shows 95% accuracy in early cancer detection"},
  {"title": "European Green Tech Innovation", "region": "Europe", "category": "Technology", "importance": 8, "description": "New renewable energy storage breakthrough"}
]`;

    const message = await getGroqClient().chat.completions.create({
      model: 'llama-3.3-70b-versatile',
      messages: [
        {
          role: 'user',
          content: prompt,
        },
      ],
      max_tokens: 2048,
      temperature: 0.7,
    });

    const responseText = message.choices[0]?.message?.content || '[]';

    // Parse JSON response - handle potential markdown formatting
    let topics = [];
    try {
      const jsonMatch = responseText.match(/\[[\s\S]*\]/);
      const jsonStr = jsonMatch ? jsonMatch[0] : responseText;
      topics = JSON.parse(jsonStr);

      // Validate and filter topics
      topics = topics.filter(
        topic =>
          topic.title &&
          topic.region &&
          topic.category &&
          typeof topic.importance === 'number' &&
          topic.importance >= 1 &&
          topic.importance <= 10
      );

      topics = topics.map(topic => ({
        ...topic,
        category: normalizeCategory(topic.category),
      }));

      console.log(`✓ Fetched ${topics.length} trending topics from Groq`);
      return { topics, success: true };
    } catch (parseError) {
      console.error('Error parsing Groq JSON response:', parseError.message);
      console.log('Raw response:', responseText.substring(0, 200));
      return { topics: [], success: false };
    }
  } catch (error) {
    console.error('Error fetching trending topics from Groq:', error.message);
    return { topics: [], success: false };
  }
};

const fetchFallbackTopicForCategory = async category => {
  try {
    const prompt = `Return one globally relevant trending topic right now for the category "${category}".

Rules:
- Category must be exactly "${category}"
- Region must be one of: ${TREND_CONFIG.regions.join(', ')}
- Importance must be a number 1-10
- Topic must be factual and non-controversial

Return ONLY valid JSON object (no markdown):
{"title":"...","region":"...","category":"${category}","importance":7,"description":"..."}`;

    const message = await getGroqClient().chat.completions.create({
      model: 'llama-3.3-70b-versatile',
      messages: [{ role: 'user', content: prompt }],
      max_tokens: 384,
      temperature: 0.6,
    });

    const responseText = message.choices[0]?.message?.content || '{}';
    const jsonMatch = responseText.match(/\{[\s\S]*\}/);
    const candidate = JSON.parse(jsonMatch ? jsonMatch[0] : responseText);

    if (
      candidate?.title &&
      candidate?.region &&
      typeof candidate?.importance === 'number' &&
      candidate.importance >= 1 &&
      candidate.importance <= 10
    ) {
      return {
        ...candidate,
        category,
      };
    }

    return null;
  } catch (error) {
    console.warn(`Warning: fallback topic fetch failed for ${category}:`, error.message);
    return null;
  }
};

/**
 * Generate blog content for a trending topic using Groq API
 */
const generateBlogContent = async topic => {
  try {
    const prompt = `Based on this trending topic, write a neutral, engaging, and informative blog post (400-600 words). Focus on facts and avoid any political bias or controversial opinions.

Topic Title: "${topic.title}"
Topic Description: ${topic.description}
Region: ${topic.region}
Category: ${topic.category}

Instructions:
- Write in a calm, professional tone suitable for a blog
- Include relevant details and insights about why this topic is trending
- Structure with clear paragraphs and sections
- Avoid sensationalism or controversy
- Use markdown formatting for better readability (headers, bold, bullet points)
- Make it engaging and informative
- Focus on the topic's significance and impact`;

    const message = await getGroqClient().chat.completions.create({
      model: 'llama-3.3-70b-versatile',
      messages: [
        {
          role: 'user',
          content: prompt,
        },
      ],
      max_tokens: 1024,
      temperature: 0.7,
    });

    return message.choices[0]?.message?.content || '';
  } catch (error) {
    console.error('Error generating blog content:', error.message);
    return '';
  }
};

/**
 * Extract keywords from article title for better image search
 */
const extractKeywordsFromTitle = title => {
  // Remove common words and extract meaningful keywords
  const stopWords = [
    'the',
    'a',
    'an',
    'and',
    'or',
    'but',
    'in',
    'on',
    'at',
    'to',
    'for',
    'of',
    'with',
    'by',
    'from',
    'is',
    'are',
    'was',
    'were',
  ];

  const words = title
    .toLowerCase()
    .split(/\s+/)
    .filter(word => !stopWords.includes(word) && word.length > 3)
    .slice(0, 3); // Take first 3 meaningful words

  return words.length > 0 ? words.join(' ') : title.substring(0, 40);
};

/**
 * Fetch featured image from Unsplash with attribution data
 * Returns full photo object with hotlink URL and photographer info
 * Has fallbacks for when primary search doesn't return results
 */
const fetchUnsplashImage = async (
  query,
  articleTitle,
  category,
  region,
  { excludedPhotoIds = new Set(), excludedImageUrls = new Set() } = {}
) => {
  try {
    if (!hasUnsplashKey()) {
      return null;
    }

    // Try primary search with article title keywords first
    const primaryQuery = articleTitle ? extractKeywordsFromTitle(articleTitle) : query;

    const searchQueries = [
      primaryQuery,
      `${category || 'news'} ${region || ''}`.trim(),
      category || 'nature',
      `${query || category || 'news'} global trend`,
      'articles news',
    ];

    let duplicateCandidate = null;

    for (const searchQuery of searchQueries) {
      const response = await axios.get('https://api.unsplash.com/search/photos', {
        params: {
          query: searchQuery,
          per_page: 20, // Increase pool to reduce repeated image reuse
          orientation: 'landscape',
          client_id: process.env.UNSPLASH_ACCESS_KEY,
        },
      });

      const photos = response?.data?.results || [];
      if (photos.length === 0) {
        continue;
      }

      const shuffled = shuffleArray(photos);
      const uniquePhoto = shuffled.find(photo => {
        const imageUrl = photo?.urls?.regular;
        return (
          photo?.id &&
          imageUrl &&
          !excludedPhotoIds.has(photo.id) &&
          !excludedImageUrls.has(imageUrl)
        );
      });

      const selectedPhoto = uniquePhoto || shuffled[0];
      if (!selectedPhoto) {
        continue;
      }

      const imagePayload = {
        imageUrl: selectedPhoto.urls.regular,
        unsplashPhotoId: selectedPhoto.id,
        photographerName: selectedPhoto.user.name,
        photographerUsername: selectedPhoto.user.username,
        photographerUrl: selectedPhoto.user.links.html,
        unsplashUrl: selectedPhoto.links.html,
        downloadTrackingUrl: selectedPhoto.links.download_location,
      };

      if (uniquePhoto) {
        return imagePayload;
      }

      if (!duplicateCandidate) {
        duplicateCandidate = imagePayload;
      }
    }

    // As a last resort, return one duplicate image instead of no image.
    if (duplicateCandidate) {
      console.log('⚠ Using duplicate Unsplash image as last-resort fallback');
      return duplicateCandidate;
    }

    return null;
  } catch (error) {
    console.error('Error fetching Unsplash image:', error.message);
    return null;
  }
};

/**
 * Trigger download tracking event on Unsplash
 * Required for production tier - counts as a download
 */
const triggerUnsplashDownload = async downloadTrackingUrl => {
  try {
    if (!downloadTrackingUrl) return;

    await axios.get(downloadTrackingUrl, {
      params: {
        client_id: process.env.UNSPLASH_ACCESS_KEY,
      },
    });

    console.log('✓ Unsplash download tracked');
  } catch (error) {
    // Non-critical error, don't fail the whole process
    console.warn('Warning: Could not track Unsplash download:', error.message);
  }
};

/**
 * Create auto-generated blog posts from trending topics across multiple regions
 */
const createAutoBlog = async () => {
  try {
    if (!hasRequiredApiKeys()) return;

    console.log('🤖 Starting auto-blog generation from trending topics...');

    // Find or create system user
    let systemUser = await User.findOne({ email: 'system@vibeblog.ai' });
    if (!systemUser) {
      systemUser = await User.create({
        name: 'Admin',
        email: 'system@vibeblog.ai',
        password: 'system-password-' + Math.random().toString(36),
      });
    }

    const { categoryCountMap, missingCategories } = await getRecentCategoryCoverage();

    // Fetch trending topics from Groq for multiple regions and categories
    const { topics, success } = await fetchTrendingTopicsFromGroq(missingCategories);

    if (!success || !topics || topics.length === 0) {
      console.log('❌ No trending topics fetched from Groq');
      return;
    }

    console.log(`✓ Fetched ${topics.length} trending topics from Groq`);

    // Filter topics by importance threshold
    const importantTopics = topics.filter(
      topic => topic.importance >= TREND_CONFIG.importanceThreshold
    );

    if (importantTopics.length === 0) {
      console.log(`⚠ No topics above importance threshold (${TREND_CONFIG.importanceThreshold})`);
      return;
    }

    const presentCategorySet = new Set(importantTopics.map(topic => topic.category));
    const missingStillAbsent = missingCategories.filter(
      category => !presentCategorySet.has(category)
    );

    const fallbackTopics =
      missingStillAbsent.length > 0
        ? (
            await Promise.all(
              missingStillAbsent.map(category => fetchFallbackTopicForCategory(category))
            )
          ).filter(Boolean)
        : [];

    const candidateTopics = [...importantTopics, ...fallbackTopics];

    // Prioritize categories that have fewer recent blogs, then higher importance.
    const sortedByCoverageAndImportance = [...candidateTopics].sort((a, b) => {
      const categoryDiff =
        (categoryCountMap.get(a.category) ?? 0) - (categoryCountMap.get(b.category) ?? 0);
      if (categoryDiff !== 0) return categoryDiff;
      return b.importance - a.importance;
    });

    const selectedTopics = [];
    const selectedCategories = new Set();

    // First pass: explicitly fill missing categories when available.
    for (const missingCategory of missingCategories) {
      if (selectedTopics.length >= TREND_CONFIG.maxBlogsPerRun) break;
      const candidate = sortedByCoverageAndImportance.find(
        topic =>
          topic.category === missingCategory &&
          !selectedTopics.some(selected => selected.title === topic.title)
      );
      if (candidate) {
        selectedTopics.push(candidate);
        selectedCategories.add(candidate.category);
      }
    }

    // First pass: maximize category diversity.
    for (const topic of sortedByCoverageAndImportance) {
      if (selectedTopics.length >= TREND_CONFIG.maxBlogsPerRun) break;
      if (selectedCategories.has(topic.category)) continue;
      selectedTopics.push(topic);
      selectedCategories.add(topic.category);
    }

    // Second pass: fill remaining slots by importance while avoiding duplicates.
    if (selectedTopics.length < TREND_CONFIG.maxBlogsPerRun) {
      const selectedTitleSet = new Set(selectedTopics.map(topic => topic.title));
      for (const topic of [...candidateTopics].sort((a, b) => b.importance - a.importance)) {
        if (selectedTopics.length >= TREND_CONFIG.maxBlogsPerRun) break;
        if (selectedTitleSet.has(topic.title)) continue;
        selectedTopics.push(topic);
        selectedTitleSet.add(topic.title);
      }
    }

    console.log(
      `📌 Creating blogs from ${selectedTopics.length} selected topics (importance ≥ ${TREND_CONFIG.importanceThreshold})...`
    );

    const recentAutoBlogs = await Blog.find({
      autoGenerated: true,
      createdAt: { $gte: new Date(Date.now() - 24 * 60 * 60 * 1000) },
    })
      .select('title imageUrl unsplashAttribution.unsplashPhotoId')
      .lean();

    const recentTitleFingerprints = new Set(
      recentAutoBlogs.map(blog => normalizeTitleFingerprint(blog.title)).filter(Boolean)
    );

    const imageCoverageWindowStart = new Date();
    imageCoverageWindowStart.setDate(
      imageCoverageWindowStart.getDate() - IMAGE_DIVERSITY_WINDOW_DAYS
    );

    const recentlyUsedImages = await Blog.find({
      autoGenerated: true,
      createdAt: { $gte: imageCoverageWindowStart },
    })
      .select('imageUrl unsplashAttribution.unsplashPhotoId')
      .lean();

    const usedPhotoIds = new Set(
      recentlyUsedImages.map(blog => blog?.unsplashAttribution?.unsplashPhotoId).filter(Boolean)
    );
    const usedImageUrls = new Set(recentlyUsedImages.map(blog => blog.imageUrl).filter(Boolean));

    const topicsWithData = [];
    for (const topic of selectedTopics) {
      try {
        // Check for duplicate: existing blog with same normalized title from last 24 hours
        const normalizedFingerprint = normalizeTitleFingerprint(topic.title);
        if (recentTitleFingerprints.has(normalizedFingerprint)) {
          console.log(`⊘ Skipping duplicate: "${topic.title}"`);
          continue;
        }

        recentTitleFingerprints.add(normalizedFingerprint);

        // Keep content and image generation parallel for each topic,
        // while processing topics sequentially to preserve image uniqueness tracking.
        const [content, imageData] = await Promise.all([
          generateBlogContent(topic),
          fetchUnsplashImage(topic.category, topic.title, topic.category, topic.region, {
            excludedPhotoIds: usedPhotoIds,
            excludedImageUrls: usedImageUrls,
          }),
        ]);

        if (!content || content.trim().length === 0) {
          console.log(`❌ Failed to generate content for: "${topic.title}"`);
          continue;
        }

        if (imageData?.unsplashPhotoId) usedPhotoIds.add(imageData.unsplashPhotoId);
        if (imageData?.imageUrl) usedImageUrls.add(imageData.imageUrl);

        topicsWithData.push({ topic, content, imageData });
      } catch (error) {
        console.error(`Error preparing topic "${topic.title}":`, error.message);
      }
    }

    const createdBlogs = [];
    const importanceScores = [];

    // Create blog for each topic that passed validation
    for (const item of topicsWithData) {
      if (!item) continue;

      try {
        const { topic, content, imageData } = item;

        // Create and save blog post
        const blog = new Blog({
          title: topic.title,
          content,
          category: topic.category,
          author: systemUser._id,
          autoGenerated: true,
          imageUrl: imageData?.imageUrl,
          unsplashAttribution: imageData
            ? {
                photographerName: imageData.photographerName,
                photographerUsername: imageData.photographerUsername,
                photographerUrl: imageData.photographerUrl,
                unsplashPhotoId: imageData.unsplashPhotoId,
                unsplashUrl: imageData.unsplashUrl,
                downloadTrackingUrl: imageData.downloadTrackingUrl,
              }
            : undefined,
          trendingMetadata: {
            region: topic.region,
            importance: topic.importance,
            description: topic.description,
          },
        });

        await blog.save();

        // Track download on Unsplash
        if (imageData?.downloadTrackingUrl) {
          await triggerUnsplashDownload(imageData.downloadTrackingUrl);
        }

        createdBlogs.push(blog);
        importanceScores.push(topic.importance);

        console.log(
          `✓ Blog created: "${blog.title}" (Region: ${topic.region}, Importance: ${topic.importance}/10)`
        );
      } catch (topicError) {
        console.error(`Error processing topic "${topic.title}":`, topicError.message);
      }
    }

    // Summary logging
    if (createdBlogs.length > 0) {
      cache.clear();
      console.log(`\n✅ Successfully created ${createdBlogs.length} auto-blogs!`);
      createdBlogs.forEach((blog, idx) => {
        console.log(`   ${idx + 1}. "${blog.title}" (Importance: ${importanceScores[idx]}/10)`);
      });
    } else {
      console.log('⚠ No blogs were created from trending topics');
    }
  } catch (error) {
    console.error('❌ Error in auto-blog generation:', error.message);
  }
};

export const runAutoBlogGeneration = async reason => {
  if (isAutoBlogGenerationRunning) {
    console.log('⏳ Auto-blog generation skipped: previous run still in progress');
    return;
  }

  isAutoBlogGenerationRunning = true;

  try {
    if (reason) {
      console.log(`\n🔁 Auto-blog generation trigger: ${reason}`);
    }
    await createAutoBlog();
  } finally {
    isAutoBlogGenerationRunning = false;
  }
};

export const refreshBlogsIfStale = async maxAgeHours => {
  try {
    const maxAgeMs = maxAgeHours * 60 * 60 * 1000;
    const latestAutoBlog = await Blog.findOne({ autoGenerated: true })
      .sort({ createdAt: -1 })
      .select('createdAt title');

    if (!latestAutoBlog) {
      console.log('📭 No auto-generated blogs found. Triggering generation...');
      await runAutoBlogGeneration('no auto-generated blogs in database');
      return;
    }

    const ageMs = Date.now() - new Date(latestAutoBlog.createdAt).getTime();
    const ageHours = Math.floor(ageMs / (1000 * 60 * 60));

    if (ageMs > maxAgeMs) {
      console.log(`📌 Latest auto-blog is ${ageHours}h old. Refreshing trending blogs...`);
      await runAutoBlogGeneration(`latest auto-blog older than ${maxAgeHours}h`);
      return;
    }

    // Keep category mix healthy even if latest blog is fresh.
    const { missingCategories } = await getRecentCategoryCoverage();

    if (missingCategories.length > 0) {
      console.log(
        `📚 Missing recent categories (${missingCategories.join(', ')}). Triggering balancing generation...`
      );
      await runAutoBlogGeneration(
        `missing categories in last ${TREND_CONFIG.coverageWindowDays} days`
      );
      return;
    }

    console.log(`✓ Auto-blogs are fresh (latest is ${ageHours}h old: "${latestAutoBlog.title}")`);
  } catch (error) {
    console.error('Error checking auto-blog freshness:', error.message);
  }
};

/**
 * Schedule daily blog generation at 00:00 UTC AND on server startup
 */
export const scheduleAutoBlogGeneration = () => {
  // Run immediately on startup to refresh content
  console.log('🔄 Refreshing blog content on startup...');
  refreshBlogsIfStale(24); // Refresh if latest blog is older than 24 hours

  // Run at 00:00 UTC every day (daily refresh)
  cron.schedule('0 0 * * *', async () => {
    console.log('\n📅 [CRON] Running scheduled auto-blog generation (00:00 UTC)...');
    try {
      await runAutoBlogGeneration('daily schedule at 00:00 UTC');
      console.log('✅ [CRON] Daily auto-blog generation completed successfully.');
    } catch (err) {
      console.error('❌ [CRON] Daily auto-blog generation failed:', err.message);
    }
  });

  // Backup schedule for hosts that sleep/restart around midnight UTC.
  cron.schedule('0 */2 * * *', async () => {
    console.log('\n🕑 [CRON] Running backup freshness check (every 2 hours)...');
    try {
      await refreshBlogsIfStale(6);
      console.log('✅ [CRON] Backup freshness check completed.');
    } catch (err) {
      console.error('❌ [CRON] Backup freshness check failed:', err.message);
    }
  });

  console.log('✓ [CRON] Auto-blog generation scheduled for 00:00 UTC daily');
  console.log('✓ [CRON] Auto-blog freshness check scheduled every 2 hours');
};

/**
 * Manual trigger for testing (generates 5 posts on startup if in development)
 * Runs in background with promise to track completion
 */
export const generateInitialBlogs = async () => {
  try {
    const blogCount = await Blog.countDocuments({ autoGenerated: true });

    console.log('🌱 Checking if initial blogs are needed...');
    console.log(`   Current auto-generated blogs: ${blogCount}`);

    // Always generate on startup for testing/demos
    if (blogCount < 5) {
      console.log('🚀 Generating initial auto-blogs on startup...');
      console.log('   (This may take a few minutes - generating diverse content)');

      const bootstrapRuns = 3; // Reduced from 5 to avoid long startup times
      const timeoutMs = 60000; // 60 second timeout per generation pass

      for (let i = 0; i < bootstrapRuns; i++) {
        console.log(`   [${i + 1}/${bootstrapRuns}] Running generation pass...`);
        try {
          // Run with timeout to prevent hanging
          await Promise.race([
            runAutoBlogGeneration(`startup bootstrap run ${i + 1}/${bootstrapRuns}`),
            new Promise((_, reject) =>
              setTimeout(() => reject(new Error(`Generation pass ${i + 1} timed out after ${timeoutMs}ms`)), timeoutMs)
            )
          ]);
        } catch (passError) {
          console.warn(`   ⚠ Generation pass ${i + 1} failed: ${passError.message}`);
          console.warn('   Continuing with next pass...');
        }
      }

      console.log('✅ Initial blog generation completed on startup');
    } else {
      console.log('✓ Sufficient auto-blogs exist, skipping initial generation');
    }
  } catch (error) {
    console.error('❌ Initial blog generation failed:', error.message);
    console.error('   Server will continue - you can manually trigger generation later');
  }
};

