import { useState } from 'react';
import { Link } from 'react-router-dom';
import { formatDate, truncateText, bufferToImageUrl, estimateReadingTime } from '../lib/utils';
import { Zap, TrendingUp, Globe } from 'lucide-react';

/**
 * Blog card component for feed listing
 */
export default function BlogCard({ blog }) {
  // Use image URL from database
  const [imageFailed, setImageFailed] = useState(false);
  const imageUrl = blog.imageUrl || null;
  const readingTime = estimateReadingTime(blog.content);
  const { trendingMetadata } = blog;
  const authorName =
    blog.author?.name === 'VibeBlog AI' ? 'Admin' : blog.author?.name || 'Anonymous';

  // Get badge color based on category
  const getCategoryColor = category => {
    const colors = {
      Technology: 'bg-blue-500/20 text-blue-400',
      Business: 'bg-purple-500/20 text-purple-400',
      Science: 'bg-cyan-500/20 text-cyan-400',
      Health: 'bg-green-500/20 text-green-400',
      Sports: 'bg-red-500/20 text-red-400',
      Economy: 'bg-yellow-500/20 text-yellow-400',
      Environment: 'bg-emerald-500/20 text-emerald-400',
      Education: 'bg-indigo-500/20 text-indigo-400',
      General: 'badge-primary',
    };
    return colors[category] || 'badge-primary';
  };

  // Get trending importance color
  const getImportanceColor = importance => {
    if (importance >= 9)
      return 'text-white bg-rose-600 border border-rose-300/40 shadow-lg shadow-rose-900/40';
    if (importance >= 7)
      return 'text-white bg-amber-500 border border-amber-200/50 shadow-lg shadow-amber-900/30';
    if (importance >= 6)
      return 'text-white bg-emerald-600 border border-emerald-200/40 shadow-lg shadow-emerald-900/30';
    return 'text-slate-100 bg-slate-600 border border-slate-200/30 shadow-md shadow-slate-900/25';
  };

  return (
    <Link
      to={`/blog/${blog.slug || blog._id}`}
      className="group card overflow-hidden border border-muted/20 hover:border-primary/30 hover:shadow-soft-hover transition-all duration-300"
    >
      {/* Image Container */}
      <div className="relative h-52 mb-4 overflow-hidden rounded-xl bg-gradient-to-br from-surface/80 to-surface flex items-center justify-center">
        {imageUrl && !imageFailed ? (
          <img
            src={imageUrl}
            alt={blog.title}
            className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
            loading="lazy"
            onError={() => setImageFailed(true)}
          />
        ) : (
          <div className="w-full h-full bg-gradient-to-br from-primary/20 to-primary/10 flex items-center justify-center relative overflow-hidden">
            <div className="absolute inset-0 bg-primary/5"></div>
            <div className="relative z-10 text-center">
              <div className="text-primary/60 text-4xl font-bold mb-2">📰</div>
              <p className="text-muted text-sm font-medium">Featured Article</p>
            </div>
          </div>
        )}

        {/* Trending Badge */}
        {blog.autoGenerated && trendingMetadata?.importance && (
          <div className="absolute top-3 right-3 flex items-center gap-2">
            <div
              className={`flex items-center gap-1 px-2 py-1 rounded-full text-xs font-bold ${getImportanceColor(trendingMetadata.importance)} backdrop-blur-sm`}
            >
              <TrendingUp size={14} />
              <span>{trendingMetadata.importance}/10</span>
            </div>
          </div>
        )}
      </div>

      {/* Content */}
      <div className="space-y-3.5">
        {/* Category Badge & Region */}
        <div className="flex items-center gap-2 flex-wrap">
          <span
            className={`badge ${getCategoryColor(blog.category)} text-xs font-semibold px-3 py-1`}
          >
            {blog.category || 'General'}
          </span>
          {trendingMetadata?.region && (
            <span className="flex items-center gap-1 text-xs font-medium bg-primary/10 text-primary px-2 py-1 rounded-full">
              <Globe size={12} />
              {trendingMetadata.region}
            </span>
          )}
        </div>

        {/* Title */}
        <h3 className="text-lg font-bold text-text group-hover:text-primary transition-colors line-clamp-2 leading-tight">
          {blog.title}
        </h3>

        {/* Excerpt */}
        <p className="text-sm text-muted line-clamp-2 leading-relaxed min-h-[2.8rem]">
          {truncateText(blog.content.replace(/[#*`\[\]()]/g, ''), 120)}
        </p>

        {/* Meta */}
        <div className="flex items-center justify-between pt-3 text-xs text-muted border-t border-muted/30">
          <span className="font-medium">{formatDate(blog.createdAt)}</span>
          <span className="bg-primary/15 text-primary px-2.5 py-1 rounded-full font-semibold">
            {readingTime} min
          </span>
        </div>

        {/* Author */}
        {blog.author && (
          <div className="pt-1 pb-0.5 flex items-center justify-between text-xs">
            <p className="text-muted">
              By <span className="text-text font-semibold">{authorName}</span>
            </p>
            {blog.autoGenerated && (
              <span className="inline-flex items-center gap-1 text-[11px] font-medium text-primary bg-primary/10 px-2 py-0.5 rounded-full">
                <Zap size={12} />
                AI
              </span>
            )}
          </div>
        )}
      </div>
    </Link>
  );
}
